# Generated by Django 3.1.10 on 2021-05-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
